import React, { useState } from 'react';
import { useStripe, useElements, CardElement } from '@stripe/react-stripe-js';
import { createPortal } from 'react-dom';
import { IconAlertCircle, IconLock, IconCreditCard } from '../icons';

/**
 * CheckoutModal component for handling Stripe payments (Auth-and-Hold).
 * 
 * Why: This component uses the Stripe Elements SDK to securely collect card details
 * and confirm the PaymentIntent without the sensitive data ever touching our server.
 */
const CheckoutModal = ({ isOpen, onClose, clientSecret, taskTitle, stakeAmount, onSuccess }) => {
    const stripe = useStripe();
    const elements = useElements();
    const [isProcessing, setIsProcessing] = useState(false);
    const [error, setError] = useState(null);

    if (!isOpen) return null;

    const handleSubmit = async (event) => {
        event.preventDefault();

        if (!stripe || !elements) {
            // Stripe.js has not loaded yet. Make sure to disable
            // form submission until Stripe.js has loaded.
            return;
        }

        setIsProcessing(true);
        setError(null);

        // Confirm the PaymentIntent with the card details provided in CardElement
        // Important: We are using the clientSecret generated by the backend.
        const { error: stripeError, paymentIntent } = await stripe.confirmCardPayment(clientSecret, {
            payment_method: {
                card: elements.getElement(CardElement),
            },
        });

        if (stripeError) {
            setError(stripeError.message);
            setIsProcessing(false);
        } else if (paymentIntent.status === 'requires_capture') {
            // Success! The hold is successfully placed.
            // Note: status 'requires_capture' is specific to manual capture (auth-and-hold).
            onSuccess();
            onClose();
        } else {
            setError("Unexpected payment state. Please contact support.");
            setIsProcessing(false);
        }
    };

    const cardElementOptions = {
        style: {
            base: {
                fontSize: '16px',
                color: '#1e293b',
                fontFamily: 'Inter, system-ui, sans-serif',
                '::placeholder': {
                    color: '#94a3b8',
                },
            },
            invalid: {
                color: '#ef4444',
            },
        },
    };

    return createPortal(
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm slide-in">
            <div className="modal-panel w-full max-w-md bg-white rounded-2xl shadow-2xl overflow-hidden">
                {/* Header */}
                <div className="bg-slate-50 px-6 py-4 border-b border-slate-100 flex items-center justify-between">
                    <h2 className="text-lg font-bold text-slate-800">Secure Stake Hold</h2>
                    <button onClick={onClose} className="text-slate-400 hover:text-slate-600 transition-colors">
                        <svg width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth="2">
                            <path d="M18 6L6 18M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-6">
                    {/* Task Summary */}
                    <div className="space-y-1">
                        <p className="text-sm text-slate-500 uppercase tracking-wider font-semibold">Staking For</p>
                        <p className="text-lg font-bold text-slate-900 truncate">{taskTitle}</p>
                        <p className="text-2xl font-black text-blue-600">₹{stakeAmount}</p>
                    </div>

                    {/* Card Input */}
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-slate-700 flex items-center gap-2">
                            <IconCreditCard className="w-4 h-4" />
                            Card Details
                        </label>
                        <div className="p-4 border border-slate-200 rounded-xl bg-slate-50 focus-within:border-blue-500 focus-within:ring-1 focus-within:ring-blue-500 transition-all">
                            <CardElement options={cardElementOptions} />
                        </div>
                    </div>

                    {/* Feedback */}
                    {error && (
                        <div className="flex items-start gap-3 p-3 bg-red-50 border border-red-100 rounded-lg text-red-600 text-sm">
                            <IconAlertCircle className="w-5 h-5 flex-shrink-0" />
                            <p>{error}</p>
                        </div>
                    )}

                    <div className="space-y-3">
                        <button
                            type="submit"
                            disabled={!stripe || isProcessing}
                            className={`w-full py-4 rounded-xl font-bold text-white transition-all flex items-center justify-center gap-2 
                                ${isProcessing ? 'bg-slate-400' : 'bg-blue-600 hover:bg-blue-700 active:scale-[0.98]'}`}
                        >
                            {isProcessing ? (
                                <>
                                    <span className="spinner w-5 h-5 !border-white/30 !border-t-white" />
                                    Authorizing...
                                </>
                            ) : (
                                <>
                                    <IconLock className="w-4 h-4" />
                                    Authorize ₹{stakeAmount} Hold
                                </>
                            )}
                        </button>
                        <p className="text-[10px] text-center text-slate-400 leading-relaxed uppercase tracking-widest">
                            Authorized but not charged. Funds are held until task completion or failure.
                        </p>
                    </div>
                </form>
            </div>
        </div>,
        document.body
    );
};

export default CheckoutModal;
