import React, { useState } from 'react';
import { useStripe, useElements, CardElement } from '@stripe/react-stripe-js';
import { createPortal } from 'react-dom';
import { IconAlertCircle, IconLock, IconCreditCard } from '../icons';
import contractService from '../../services/contract.service';

/**
 * CheckoutModal component for handling Stripe payments (Auth-and-Hold).
 * 
 * Why: This component uses the Stripe Elements SDK to securely collect card details
 * and confirm the PaymentIntent without the sensitive data ever touching our server.
 */
const CheckoutModal = ({ isOpen, onClose, clientSecret, taskTitle, stakeAmount, onSuccess }) => {
    const stripe = useStripe();
    const elements = useElements();
    const [isProcessing, setIsProcessing] = useState(false);
    const [error, setError] = useState(null);

    if (!isOpen) return null;

    const handleSubmit = async (event) => {
        event.preventDefault();

        if (!stripe || !elements) {
            // Stripe.js has not loaded yet. Make sure to disable
            // form submission until Stripe.js has loaded.
            return;
        }

        setIsProcessing(true);
        setError(null);

        // Confirm the PaymentIntent with the card details provided in CardElement
        // Important: We are using the clientSecret generated by the backend.
        const { error: stripeError, paymentIntent } = await stripe.confirmCardPayment(clientSecret, {
            payment_method: {
                card: elements.getElement(CardElement),
            },
        });

        if (stripeError) {
            setError(stripeError.message);
            setIsProcessing(false);
        } else if (paymentIntent.status === 'requires_capture') {
            // Success! The hold is successfully placed on Stripe.
            // But we MUST notify our backend to mark the task as ACTIVE.
            try {
                await contractService.verifyPayment(paymentIntent.id);
                onSuccess();
                onClose();
            } catch (err) {
                console.error("Backend verification failed:", err);
                setError("Payment authorized but failed to activate task. Please contact support.");
                setIsProcessing(false);
            }
        } else {
            setError("Unexpected payment state. Please contact support.");
            setIsProcessing(false);
        }
    };

    const cardElementOptions = {
        style: {
            base: {
                fontSize: '16px',
                color: '#1e293b',
                fontFamily: 'Inter, system-ui, sans-serif',
                '::placeholder': {
                    color: '#94a3b8',
                },
            },
            invalid: {
                color: '#ef4444',
            },
        },
    };

    return createPortal(
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-md animate-in fade-in duration-300">
            <div className="modal-panel w-full max-w-lg flex flex-col gap-8 bg-white/95 rounded-[2rem] p-10 shadow-[0_32px_80px_-15px_rgba(15,23,42,0.2)] border border-white/60 animate-in zoom-in-95 slide-in-from-bottom-8 duration-500">
                
                {/* Header */}
                <div className="flex items-start justify-between">
                    <div className="space-y-2">
                        <h2 className="text-3xl font-black text-slate-900 tracking-tight leading-none">
                            Secure Stake
                        </h2>
                        <p className="text-[14px] text-slate-500 font-medium leading-relaxed">
                            Authorize the hold to start your task.
                        </p>
                    </div>

                    <button
                        onClick={onClose}
                        disabled={isProcessing}
                        className="group p-3 text-slate-400 hover:text-slate-900 hover:bg-slate-100/80 rounded-2xl transition-all duration-300"
                        aria-label="Close dialog"
                    >
                        <svg width="24" height="24" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth="2.5" className="group-hover:rotate-90 transition-transform duration-300">
                            <path d="M18 6L6 18M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="flex flex-col gap-8">
                    {/* Task Hero Summary */}
                    <div className="relative overflow-hidden p-6 bg-slate-50/50 rounded-3xl border border-slate-100 flex items-center justify-between">
                        <div className="space-y-1 relative z-10">
                            <p className="text-[11px] font-black text-slate-400 uppercase tracking-widest leading-none">Your Stake</p>
                            <p className="text-lg font-extrabold text-slate-800 truncate max-w-[200px]">{taskTitle}</p>
                        </div>
                        <div className="text-right relative z-10">
                            <p className="text-4xl font-black text-blue-600 tracking-tight">₹{stakeAmount}</p>
                        </div>
                        <div className="absolute top-0 right-0 p-4 opacity-[0.05]">
                            <IconCreditCard className="w-20 h-20" />
                        </div>
                    </div>

                    {/* Card Input Section */}
                    <div className="space-y-3">
                        <label className="text-[13px] font-bold text-slate-500 uppercase tracking-wider px-1">
                            Payment Details
                        </label>
                        <div className="p-5 border border-slate-200 rounded-2xl bg-white shadow-sm ring-1 ring-slate-100 focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-500/20 transition-all duration-300">
                            <CardElement options={cardElementOptions} />
                        </div>
                    </div>

                    {/* Feedback */}
                    {error && (
                        <div className="flex items-center gap-4 p-5 bg-red-50 border border-red-100 rounded-2xl text-red-700 animate-in slide-in-from-top-4 duration-300">
                            <div className="p-2 bg-red-100 rounded-lg">
                                <IconAlertCircle className="w-5 h-5 text-red-600" />
                            </div>
                            <span className="text-sm font-bold leading-tight">{error}</span>
                        </div>
                    )}

                    {/* Actions */}
                    <div className="space-y-4">
                        <button
                            type="submit"
                            disabled={!stripe || isProcessing}
                            className={`group w-full py-6 rounded-2xl font-black text-lg transition-all duration-300 flex items-center justify-center gap-4 relative overflow-hidden active:scale-[0.98]
                                ${isProcessing ? 'bg-slate-200 cursor-not-allowed' : 'text-white'}`}
                            style={!isProcessing ? { background: 'var(--brand-grad)', boxShadow: 'var(--shadow-brand)' } : {}}
                        >
                            {isProcessing ? (
                                <div className="flex items-center gap-3">
                                    <span className="spinner w-6 h-6 !border-slate-400 !border-t-slate-600" />
                                    <span className="text-slate-500 font-bold">Authorizing...</span>
                                </div>
                            ) : (
                                <>
                                    <span className="relative z-10 flex items-center gap-3">
                                        <IconLock className="w-6 h-6" />
                                        Confirm ₹{stakeAmount} Hold
                                    </span>
                                    <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity" />
                                </>
                            )}
                        </button>
                        <p className="text-[10px] text-center text-slate-400 font-bold tracking-[0.2em] uppercase px-4 leading-relaxed">
                            Secured by <span className="text-slate-600">Stripe TLS</span>. No funds leave your account until deadline.
                        </p>
                    </div>
                </form>
            </div>
        </div>,
        document.body
    );
};

export default CheckoutModal;
